name: AntiPortalTrap
version: ${project.version}-b${BUILD_NUMBER}
main: me.xCopyright.antiportaltrap.AntiPortalTrap
author: xCopyright
authors: [Samistine]
description: Prevents players from being portal trapped